name: Deploy Website to S3

on:
  push:
    branches: [ prod ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.6'
    - name: Install
      run: yarn install
    - name: Build
      run: yarn build
    - name: Test
      run: CI=true yarn test --coverage
    - name: Lint
      run: CI=true yarn lint
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: sa-east-1
    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./build/ s3://secretsanta.gkath.com --delete


